version: "3.7"

services:

  db:
      image: mariadb:10
      container_name: wpgains-demo-db
      restart: always
      volumes:
        - db_data:/var/lib/mysql
        - ./backups:/backups
      environment:
        MYSQL_DATABASE: wpgdemo
        MYSQL_USER: wpgdemo_user
        MYSQL_PASSWORD: demo#1234
        MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        MYSQL_ROOT_PASSWORD: demo#1234
      
  wordpress:
        image: wordpress:latest
        container_name: wpgains-demo-app
        restart: always
        depends_on: ['db']
        ports: ['80:80']
        links: ['db:db']
        volumes:
          - './wp-data:/var/www/html'
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_NAME: wpgdemo
          WORDPRESS_DB_USER: wpgdemo_user
          WORDPRESS_DB_PASSWORD: demo#1234

  phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name:  wpgains-demo-phpmyadmin
        restart: always       
        depends_on: ['db']
        ports: ['12000:80']
        links: ['db:db']
        environment:
          PHP_HOST: db
          PHP_USER: wpgdemo_user
          PHP_PASSWORD: demo#1234

volumes:
  db_data: {}